system_metric:
  enable: True
  memory:
    ingest_polling_interval: 5
    run_query_benchmark_polling_interval: 5

container_id: clickhouse-clp-bench
dataset_path: /home/xiaochong/develop/clp-bench-prototype/tests/datasets/hadoop-small
hot_run_warm_up_times: 3
related_processes:
  - clickhouse-server
  - clickhouse-client
queries:
  - JSON_EXISTS(raw, '$.attr.tickets')
  - JSONExtractInt(raw, 'id') = 22419
  - JSON_VALUE(raw, '$.attr.message.msg') like 'log_release%' AND JSON_VALUE(raw, '$.attr.message.session_name') = 'connection'
  - JSON_VALUE(raw, '$.ctx') = 'initandlisten' AND (JSON_VALUE(raw, '$.attr.message.msg') like 'log_remove%' OR JSON_VALUE(raw, '$.msg') != 'WiredTiger message')
  - JSON_VALUE(raw, '$.c') = 'WTWRTLOG' and JSONExtractInt(JSONExtractString(JSONExtractString(raw, 'attr'), 'message'), 'ts_sec')  > 1679490000
  - JSON_VALUE(raw, '$.ctx') = 'FlowControlRefresher' AND JSONExtractInt(JSONExtractString(raw, 'attr'), 'numTrimmed') = 0 