#!/bin/bash

set -e
set -u

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
container_name="clickhouse-clp-bench"

docker build \
	-t "$container_name" \
	"$script_dir" \
	--file "$script_dir"/Dockerfile
