#!/bin/bash

collection_name=clickhouse_clp_bench

clickhouse-client -t --max_threads 1 --query "SELECT * from ${collection_name} where $1 SETTINGS max_threads = 1, min_bytes_to_use_direct_io = 1" 2>/dev/null | wc -l