#!/bin/bash

/opt/splunk/bin/splunk add monitor "$1" -auth "admin:admin_password"

while true; do
    count=$(grep "Batch input finished reading file=" /opt/splunk/var/log/splunk/splunkd.log | grep "$1" | sed -n "s/.*file='\([^']*\)'.*/\1/p" | wc -l)
    
    if [ "$count" -eq 298 ]; then
        exit 0
    fi
    
    sleep 1
done